/**
 * ServiceNow REST API Deployment Script
 * Generated by InfinitiCode
 * Application: Clean ServiceNow Test Integration
 * Scope: x_ic_clean_test
 * Table: x_ic_clean_test_clean_servicenow_test_ci
 */

// ServiceNow instance configuration
const SN_INSTANCE = process.env.SN_INSTANCE || 'lastmile.service-now.com';
const SN_USERNAME = process.env.SN_USERNAME || 'admin';
const SN_PASSWORD = process.env.SN_PASSWORD;

if (!SN_PASSWORD) {
  console.error('SN_PASSWORD environment variable is required');
  process.exit(1);
}

const baseUrl = `https://${SN_INSTANCE}/api/now/table`;
const auth = Buffer.from(`${SN_USERNAME}:${SN_PASSWORD}`).toString('base64');

// REST API helper function
async function createRecord(table, data) {
  try {
    const response = await fetch(`${baseUrl}/${table}`, {
      method: 'POST',
      headers: {
        'Authorization': `Basic ${auth}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    });
    
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    
    const result = await response.json();
    console.log(`✅ Created ${table} record: ${result.result.sys_id}`);
    return result.result;
  } catch (error) {
    console.error(`❌ Failed to create ${table}:`, error.message);
    throw error;
  }
}

// Main deployment function
async function deployApplication() {
  console.log('🚀 Deploying Clean ServiceNow Test Integration...');
  
  try {
    // 1. Create application
    const app = await createRecord('sys_app', {
      name: 'Clean ServiceNow Test Integration',
      scope: 'x_ic_clean_test',
      vendor: 'Last Mile Inc.',
      version: '1.0.0',
      short_description: 'ServiceNow integration package',
      active: true,
      can_edit_in_studio: true
    });
    
    // 2. Create table
    const table = await createRecord('sys_db_object', {
      name: 'x_ic_clean_test_clean_servicenow_test_ci',
      label: 'Clean ServiceNow Test Integration CI',
      super_class: 'cmdb_ci_ot_field_device'
    });
    
    // 3. Create fields
    
    await createRecord('sys_dictionary', {
      name: 'x_ic_clean_test_clean_servicenow_test_ci',
      element: 'u_systemid',
      column_label: 'systemId',
      internal_type: 'string',
      max_length: 100,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_clean_test_clean_servicenow_test_ci',
      element: 'u_deviceid',
      column_label: 'deviceId',
      internal_type: 'string',
      max_length: 100,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_clean_test_clean_servicenow_test_ci',
      element: 'u_devicename',
      column_label: 'deviceName',
      internal_type: 'string',
      max_length: 100,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_clean_test_clean_servicenow_test_ci',
      element: 'u_status',
      column_label: 'status',
      internal_type: 'string',
      max_length: 100,
      mandatory: false
    });
    await createRecord('sys_dictionary', {
      name: 'x_ic_clean_test_clean_servicenow_test_ci',
      element: 'u_lastcontact',
      column_label: 'lastContact',
      internal_type: 'glide_date_time',
      max_length: 100,
      mandatory: false
    });
    
    // 4. Create navigation module
    await createRecord('sys_app_module', {
      title: 'Clean ServiceNow Test Integration CIs',
      name: 'x_ic_clean_test_clean_servicenow_test_ci',
      link_type: 'LIST',
      query: 'sys_class_name=x_ic_clean_test_clean_servicenow_test_ci'
    });
    
    console.log('✅ Deployment completed successfully!');
    console.log(`📋 Application: ${app.name} (${app.scope})`);
    console.log(`📋 Table: x_ic_clean_test_clean_servicenow_test_ci`);
    console.log(`📋 Fields: 5 custom fields created`);
    
  } catch (error) {
    console.error('💥 Deployment failed:', error.message);
    process.exit(1);
  }
}

// Run deployment
deployApplication();
